export const APP_LOADING = "APP_LOADING";
export const MESSAGE_LOADED = "MESSAGE_LOADED";
export const APP_STOPPED_LOADING = "APP_STOPPED_LOADING";
export const SHOW_ERROR= "SHOW_ERROR";
export const MENU_OPENED = "MENU_OPENED";
export const MENU_CLOSED = "MENU_CLOSED";

