source 'https://rubygems.org'

gem 'mysql2', '~>0.4.0'
gem 'puma'
gem 'rack'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'

group :development do
  gem 'byebug'
end
